homeassistant:
  # Omitted values in this section will be auto detected using freegeoip.io

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 322
  # Name of the location where Home Assistant is running
  name: Home
  # C for Celcius, F for Fahrenheit
  temperature_unit: F
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  unit_system: imperial
  customize: !include customize.yaml

zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 200
  icon: mdi:home

zone 2:
  name: Buckhead
  latitude: !secret latitude_buckhead
  longitude: !secret longitude_buckhead
  radius: 200
  icon: mdi:school

zone 3:
  name: Downtown
  latitude: !secret latitude_downtown
  longitude: !secret longitude_downtown
  radius: 200
  icon: mdi:school

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  trusted_networks:
    - 192.168.2.0/24

zeroconf:
recorder:
  purge_days: 7
# Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
conversation:

# Discover some devices automatically
discovery:
wemo:
updater:

#Adds Amazon Echo support
emulated_hue:
  expose_by_default: false

# Track the sun
sun:
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

media_player:
  - platform: sonos
    hosts: 192.168.2.150
  - platform: kodi
    host: http://192.168.2.28
    port: 8080
    name: Kodi NSTV
    user: !secret kodi_username
    password: !secret kodi_password
  - platform: panasonic_viera
    host: 192.168.2.129
    port: 55000
    name: Panasonic Viera TV
  - platform: plex
    host: 192.168.2.113

camera:
  - platform: bloomsky
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=FFC&brand=wui&num=1&delay=100&type=NTP&frame=0&scale=1&noclutter=0&showstorms=5&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24427697&lat=0&lon=0&label=you
    name: RadarGA
  # - platform: foscam
  #   ip: 192.168.2.200
  #   name: Door Camera
  #   port: 88
  #   username: !secret foscam_username
  #   password: !secret foscam_password
  # - platform: foscam
  #   ip: 192.168.2.212
  #   name: Door Camera
  #   port: 88
  #   username: !secret foscam_username
  #   password: !secret foscam_password
  # - platform: foscam
  #   ip: 192.168.2.35
  #   name: Door Camera
  #   port: 88
  #   username: !secret foscam_username
  #   password: !secret foscam_password

ifttt:
  key: !secret ifttt_key

device_tracker:
  - platform: asuswrt
    host: 192.168.2.1
    protocol: telnet
    username: !secret asus_username
    password: !secret asus_password
  - platform: owntracks
    max_gps_accuracy: 200
  - platform: unifi
    host: 192.168.2.161
    username: !secret unifi_username
    password: !secret unifi_password

notify:
  - platform: ios
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - name: telegram
    platform: telegram
    api_key: !secret telegram_key
    chat_id: !secret telegram_chatID_Alok
  - platform: ecobee
    name: ecobee

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

bloomsky:
  api_key: !secret bloomsky_key

ecobee:
  api_key: !secret ecobee_key
  hold_temp: True

logger:
  default: error
#  default: warning
#  logs:
#    homeassistant.components.notify: info
#    homeassistant.components.automation: info
#    homeassistant.components.mqtt: debug

input_select:
  abodestatus:
    name: Abode status
    options:
     - standby
     - home
     - away
    initial: standby
    icon: mdi:security

input_boolean:
  abodeupdate:
    name: Abode Updates
    initial: on
    icon: mdi:security
  startrecording:
    name: Camera Recording
    initial: off
    icon: mdi:record-rec
  alokhome:
    name: Alok Home
    initial: on
    icon: mdi:cellphone-iphone
  rashmihome:
    name: Rashmi Home
    initial: on
    icon: mdi:cellphone-iphone
  thermo_away_main:
    name: Downstairs Away Mode
    initial: off
    icon: mdi:home
  thermo_away_upstairs:
    name: Upstairs Away Mode
    initial: off
    icon: mdi:home
  alok360home:
    name: Alok Life360 Home
    initial: on
    icon: mdi:cellphone-iphone
  rashmi360home:
    name: Rashmi Life360 Home
    initial: on
    icon: mdi:cellphone-iphone

switch:
 platform: command_line
 switches:
   #Switch for Foscam Motion Detection
   foscam_record:
     command_on: 'curl -k "http://192.168.2.200:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=1&isPirAlarmEnable=1&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
     command_off: 'curl -k "http://192.168.2.200:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=0&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=0&isPirAlarmEnable=0&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
     value_template: ''
   foscam_record2:
     command_on: 'curl -k "http://192.168.2.212:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=1&isPirAlarmEnable=1&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
     command_off: 'curl -k "http://192.168.2.212:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=0&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=0&isPirAlarmEnable=0&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
     value_template: ''
   foscam_record3:
     command_on: 'curl -k "http://192.168.2.35:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=1&isPirAlarmEnable=1&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
     command_off: 'curl -k "http://192.168.2.35:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=0&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=0&isPirAlarmEnable=0&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
     value_template: ''

ios:
  push:
    categories:
      - name: Alarm
        identifier: 'ALARM'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm' # Needs to be short!
            activationMode: 'background' # foreground or background. The mode in which to run the app when the action is performed.
            authenticationRequired: yes # A Boolean value indicating whether the user must unlock the device before the action is performed.
            destructive: yes # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
            behavior: 'default' # default or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm' # Needs to be short!
            activationMode: 'background' # foreground or background. The mode in which to run the app when the action is performed.
            authenticationRequired: yes # A Boolean value indicating whether the user must unlock the device before the action is performed.
            destructive: no # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
            behavior: 'textInput' # default or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.
            textInputButtonTitle: 'Silencio!' # Only when behavior is TextInput.
            textInputPlaceholder: 'Placeholder' # Only for iOS 10 when behavior is TextInput.
# View all events in a logbook
logbook:
  exclude:
    domains:
      - sun
    entities:
      - sensor.pws_weather
      - sensor.pws_temp_f
      - sensor.pws_pressure_in
      - sensor.pws_relative_humidity
      - binary_sensor.ars_bloom_rain
      - binary_sensor.ars_bloom_night
      - sensor.ars_bloom_uvindex
      - sensor.pws_wind_dir
      - sensor.pws_wind_string
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_daily_summary
      - sensor.time__date
      - sensor.bloomlastupdate
      - sensor.garage_door_tilt_sensor_alarm_level_5_1
      - sensor.garage_door_tilt_sensor_alarm_type_5_0
      - sensor.garage_door_tilt_sensor_burglar_5_10
      - sensor.garage_door_tilt_sensor_sourcenodeid_5_2
      - sensor.garagedoorbattery
      - sensor.phonebatteryalok
      - sensor.phonebatteryrashmi
      - sensor.usd_inr
      - sensor.usd_eur
      - sensor.downstairsthermoper
      - sensor.upstairsthermostatoperation
      - group.abode_status
      - group.device_location
      - group.information
      - group.thermostats
      - group.media_player
      - device_tracker.unificloudkey
      - media_player.unnamed_device
# Enables support for tracking state changes over time.
history:
  include:
    entities:
      - binary_sensor.garagedoor
      - device_tracker.alokiosiphone
      - device_tracker.myiphone
      - device_tracker.pi_alokphone
      - device_tracker.pi_rashmiphone
      - device_tracker.rashmiappiphone
      - device_tracker.rashmisiphone
      - input_boolean.alokhome
      - input_boolean.rashmihome
      - input_select.abodestatus
      - media_player.livingroomsonos
      - media_player.panasonic_viera_tv
      - sensor.ars_bloom_temperature
      - sensor.ars_bloom_voltage
      - sensor.downstairs_temperature
      - sensor.evening_commute
      - sensor.living_room_temperature
      - sensor.morning_commute
      - sensor.plexspy
      - sensor.upstairs_temperature
      - switch.driveway

automation: !include automation.yaml
automation persistence: !include persistence.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
alexa: !include alexa.yaml
